name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Fix beasties bug
        run: node -e "const fs=require('fs');const p='node_modules/@angular/build/node_modules/beasties/dist/index.cjs';let c=fs.readFileSync(p,'utf8');c=c.replaceAll('?.insertBefore','&&c.parentNode.insertBefore');fs.writeFileSync(p,c);console.log('Fixed!');"

      - name: Build
        run: npx ng build --configuration=production

      - name: Deploy to Firebase
        run: npx firebase-tools deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}" --non-interactive